<?php

namespace AppBundle\Repository;

/**
 * PerksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerksRepository extends \Doctrine\ORM\EntityRepository
{
}
